//! Shared app-server protocol message families.
//!
//! This module is split into cohesive submodules by message family:
//! - [`auth`]: the [`AuthMode`] enum shared across protocol versions.
//! - [`fuzzy_file_search`]: fuzzy file-search params/results and notifications.
//! - [`client_requests`]: the `ClientRequest`/`ClientResponse` families plus the
//!   request-serialization-scope and experimental-gating machinery.
//! - [`server_requests`]: the `ServerRequest`/`ServerResponse` families.
//! - [`notifications`]: the `ServerNotification`/`ClientNotification` families.
//!
//! Every public item is re-exported here so external paths
//! (`crate::protocol::common::*`, and the crate-root glob in `lib.rs`) are
//! unchanged.

mod auth;
mod client_requests;
mod fuzzy_file_search;
mod notifications;
mod server_requests;

pub use auth::*;
pub use client_requests::*;
pub use fuzzy_file_search::*;
pub use notifications::*;
pub use server_requests::*;

// Preserve the existing crate-internal paths for items generated by the
// request/notification macros that are only `pub(crate)` (consumed by
// `crate::export` and `crate::schema_fixtures` via `crate::protocol::common::*`).
pub(crate) use client_requests::EXPERIMENTAL_CLIENT_METHOD_PARAM_TYPES;
pub(crate) use client_requests::EXPERIMENTAL_CLIENT_METHOD_RESPONSE_TYPES;
pub(crate) use client_requests::EXPERIMENTAL_CLIENT_METHODS;
pub(crate) use client_requests::visit_client_response_types;
pub(crate) use server_requests::visit_server_response_types;
