// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpCacheEntryState } from "./McpCacheEntryState";

export type CodexAppsToolsCacheStatus = { path: string, state: McpCacheEntryState, schemaVersion: number | null, byteSize: bigint | null, modifiedAt: bigint | null, toolCount: bigint | null, };
