// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MemoryJobStatus } from "./MemoryJobStatus";

export type MemoryStatusResponse = { featureEnabled: boolean, stateDbAvailable: boolean, memoryRoot: string, memoryRootExists: boolean, memoryIndexExists: boolean, rawMemoriesExists: boolean, stage1OutputCount: bigint | null, selectedForPhase2Count: bigint | null, latestSourceUpdatedAt: bigint | null, latestGeneratedAt: bigint | null, jobs: Array<MemoryJobStatus> | null, };
