// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewLineRange } from "./ReviewLineRange";

export type ReviewCodeLocation = { absoluteFilePath: string, lineRange: ReviewLineRange, };
