// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewFinding } from "./ReviewFinding";

export type ReviewOutput = { findings: Array<ReviewFinding>, overallCorrectness: string, overallExplanation: string, overallConfidenceScore: number, };
