$ErrorActionPreference = "Stop"
$Host.UI.RawUI.WindowTitle = 'Codex worker: solid_refactor_wave3_dependency_scout_worker'
Set-Location -LiteralPath 'C:\Users\Oleh\Documents\GitHub\open_ai\codex'
Remove-Item Env:\CODEX_THREAD_ID, Env:\CODEX_SHELL, Env:\CODEX_INTERNAL_ORIGINATOR_OVERRIDE -ErrorAction SilentlyContinue
$codexArgs = @([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('LWM=')), [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('bW9kZWw9Z3B0LTUuNQ==')), [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('LWM=')), [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('bW9kZWxfcmVhc29uaW5nX2VmZm9ydD14aGlnaA==')), [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('LS1jZA==')), [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('QzpcVXNlcnNcT2xlaFxEb2N1bWVudHNcR2l0SHViXG9wZW5fYWlcY29kZXg=')), [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('LS1hc2stZm9yLWFwcHJvdmFs')), [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('bmV2ZXI=')), [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('LS1zYW5kYm94')), [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ZGFuZ2VyLWZ1bGwtYWNjZXNz')), [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('ZXhlYw==')), [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String('IyBzb2xpZF9yZWZhY3Rvcl93YXZlM19kZXBlbmRlbmN5X3Njb3V0X3dvcmtlcgoKWW91IGFyZSBhIHNlcGFyYXRlIGV4dGVybmFsIENvZGV4IGV4ZWMgd29ya2VyIGluIGBDOlxVc2Vyc1xPbGVoXERvY3VtZW50c1xHaXRIdWJcb3Blbl9haVxjb2RleGAuCgpZb3UgYXJlIG5vdCBhbG9uZSBpbiB0aGUgY29kZWJhc2UuIE90aGVyIGV4dGVybmFsIHdvcmtlcnMgbWF5IGVkaXQgZmlsZXMuIFRoaXMgd29ya2VyIGlzIHJlYWQtb25seSBleGNlcHQgZm9yIGl0cyBoYW5kb2ZmLgoKRmlyc3QgcmVhZDoKCi0gYEFHRU5UUy5tZGAKLSBgLmNvZGV4L3dvcmtmbG93L3NvbGlkLXJlZmFjdG9yLWhhbmRvZmYubWRgCi0gYC5jb2RleC93b3JrZmxvdy9hZ2VudHMvY29yZV9ib3VuZGFyeV9yZXNpZHVhbF9pbXBvcnRfc2NvdXRfd29ya2VyLmhhbmRvZmYubWRgCgpPd25lcnNoaXA6CgotIHJlYWQtb25seSBpbnNwZWN0aW9uIGFjcm9zcyBgY29kZXgtcnMvY29yZS8qKmAsIGBjb2RleC1ycy9jb3JlLWFwaS8qKmAsIGBjb2RleC1ycy9jb3JlLWRvbWFpbi8qKmAsIGBjb2RleC1ycy90aHJlYWQtc3RvcmUqLyoqYCwgYGNvZGV4LXJzL3Rvb2xzKi8qKmAsIGFuZCBgY29kZXgtcnMvYWdlbnQtKi8qKmAKLSBoYW5kb2ZmIG9ubHk6IGAuY29kZXgvd29ya2Zsb3cvYWdlbnRzL3NvbGlkX3JlZmFjdG9yX3dhdmUzX2RlcGVuZGVuY3lfc2NvdXRfd29ya2VyLmhhbmRvZmYubWRgCgpUYXNrOgoKLSBNYXAgcmVtYWluaW5nIGRpcmVjdCBvciB0cmFuc2l0aXZlIGRlcGVuZGVuY3kgbGVha3Mgd2hlcmUgYGNvZGV4LWNvcmVgIGRlcGVuZHMgb24gY29uY3JldGUgaW1wbGVtZW50YXRpb24gZGV0YWlscyBpbnN0ZWFkIG9mIGFic3RyYWN0aW9ucy4KLSBJZGVudGlmeSB3aGljaCBhY3RpdmUgd29ya2VyIHNob3VsZCBvd24gZWFjaCBsZWFrLgotIERvIG5vdCBtYWtlIHNvdXJjZSBlZGl0cy4KCkhhcmQgY29tbWFuZCBiYW46CgotIERvIG5vdCBleGVjdXRlIGBjYXJnb2AsIGBydXN0Y2AsIGBqdXN0YCwgYGJhemVsYCwgYnVpbGQgc2NyaXB0cywgdGVzdCBzY3JpcHRzLCBzY2hlbWEgZ2VuZXJhdGlvbiwgZGVwbG95IHNjcmlwdHMsIG9yIGdpdCBzdGFnaW5nL2NvbW1pdHMuCgpBbGxvd2VkIGNvbW1hbmRzOgoKLSBSZWFkL3NlYXJjaC9zdGF0dXMvZGlmZiBjb21tYW5kcyBzdWNoIGFzIGByZ2AsIGBHZXQtQ29udGVudGAsIGBnaXQgZGlmZmAsIGBnaXQgc3RhdHVzYC4KCkhhbmRvZmY6CgpXcml0ZSB0aGUgaGFuZG9mZiB3aXRoIGZpbmRpbmdzIGdyb3VwZWQgYnkgb3duZXIsIGV2aWRlbmNlIHBhdGhzLCBhbmQgZXhhY3Qgc291cmNlL2RlcGVuZGVuY3kgY2hlY2tzIHJvb3Qgc2hvdWxkIHJ1biBsYXRlci4K')))
$redirectToLog = $true
if ($redirectToLog) {
    & 'codex' @codexArgs *>&1 | Tee-Object -FilePath 'C:\Users\Oleh\Documents\GitHub\open_ai\codex\.codex\workflow\agents\solid_refactor_wave3_dependency_scout_worker.exec.visible.log'
} else {
    & 'codex' @codexArgs
}
